### ISSUE TITLE
Security Server Installation Error

### ISSUE THREAD

**Issue by figueroarv** [nordic-institute/X-Road-development#21]
Hi,
We rebuilt the latest source code version to add support for C=AR.

Central Server was succefully installed and is runnig right, but on the Security Server installation we get "**xroad-proxy-ui-api breaks xroad-jetty9**".

I attached our install script, can you take a look and give a feedback?

[ss-install.sh.txt](https://github.com/nordic-institute/X-Road-development/files/6887830/ss-install.sh.txt)

**Comment by figueroarv** [comment]
Is xroad-jetty9 required in latest versions? Maybe this the issue...

**Comment by raits** [comment]
Hi,

Yes, it appears that you are installing the `xroad-jetty9` and `xroad-nginx` packages, which are no longer required since the new Security Server UI and API component was introduced in version 6.24.0. 

Please also note, that your packages appear to be built off of the develop branch (7.0.0), which is currently not yet stable. The latest stable version is 6.26.0.

**Comment by figueroarv** [comment]
Hi Raido,

Great! We will fix that and tray again on stable version 6.26.0.

Thank you!

**Comment by figueroarv** [comment]
We was included packages no longer required in latest version.
